#!/bin/bash
ub16_env()
{
#set kernel bridge
    modprobe br_netfilter
    echo "net.bridge.bridge-nf-call-iptables=1" >> /etc/sysctl.conf
    echo "net.bridge.bridge-nf-call-ip6tables=1" >> /etc/sysctl.conf
}

function ub16_chrony()
{
   apt  install -y chrony
   # $a means add at last in file
    if [ $controller -eq 1 ] ; then
       sed -i '$a allow '"$SERVER_IP"'\/'"$MASK_LEN"'' /etc/chrony/chrony.conf
    else
       sed -i '$a\server '"$MASTERNAME"' iburst' /etc/chrony/chrony.conf
    fi
    service chrony restart
}



function_ub16_queen()
{
    apt install -y software-properties-common
    add-apt-repository cloud-archive:queens -y
    apt update -y  && apt dist-upgrade -y
    apt install  -y python-openstackclient 
}

function_ub16_mariadb()
{
    apt install -y mariadb-server python-pymysql
    if [ ! -f /etc/mysql/mariadb.conf.d/99-openstack.cnf ] ; then
        touch /etc/mysql/mariadb.conf.d/99-openstack.cnf
    fi
    
    echo "[mysqld]" >>/etc/mysql/mariadb.conf.d/99-openstack.cnf

    sed -i '$a bind-address = '"$HOST_IP"''  /etc/mysql/mariadb.conf.d/99-openstack.cnf
    sed -i '$a default-storage-engine = innodb'  /etc/mysql/mariadb.conf.d/99-openstack.cnf
    sed -i '$a innodb_file_per_table = on'  /etc/mysql/mariadb.conf.d/99-openstack.cnf
    sed -i '$a max_connections = 4096'  /etc/mysql/mariadb.conf.d/99-openstack.cnf
    sed -i '$a collation-server = utf8_general_ci'  /etc/mysql/mariadb.conf.d/99-openstack.cnf
    sed -i '$a character-set-server = utf8'  /etc/mysql/mariadb.conf.d/99-openstack.cnf
    service mysql restart    

    echo -e "\nY\n$PASSWORD\n$PASSWORD\nY\nn\nY\nY\n" | mysql_secure_installation

}

function_ub16_rabbitmq()
{
#install RabbitMq
    apt install -y rabbitmq-server

#passwd value:smart
    rabbitmqctl add_user openstack $PASSWORD
    rabbitmqctl set_permissions openstack ".*" ".*" ".*"

}

function_ub16_memcache()
{
  #memcache install
    apt install -y memcached python-memcache
    #sed -i 's/-l 127.0.0.1,::1/-l 127.0.0.1,::1,'"$HOSTNAME"'/g' /etc/memcached.conf
    sed -i 's/-l 127.0.0.1/-l 127.0.0.1,'"$HOSTNAME"'/g' /etc/memcached.conf
    service memcached restart
}

function_ub16_etcd()
{
    apt install -y etcd
    sed -i '/^/,$d' /etc/default/etcd
    #需写入一行，sed方可继续追加
    echo "#[Member]" > /etc/default/etcd
    sed -i '$a  ETCD_DATA_DIR="/var/lib/etcd/default.etcd"' /etc/default/etcd
    sed -i '$a  ETCD_LISTEN_PEER_URLS="http://'"$HOST_IP"':2380"' /etc/default/etcd
    sed -i '$a  ETCD_LISTEN_CLIENT_URLS="http://'"$HOST_IP"':2379"' /etc/default/etcd
    sed -i '$a  ETCD_NAME="'"$HOSTNAME"'"' /etc/default/etcd
    sed -i '$a  ETCD_INITIAL_ADVERTISE_PEER_URLS="http://'"$HOST_IP"':2380"' /etc/default/etcd
    sed -i '$a  ETCD_ADVERTISE_CLIENT_URLS="http://'"$HOST_IP"':2379"' /etc/default/etcd
    sed -i '$a  ETCD_INITIAL_CLUSTER="'"$HOSTNAME"'=http://'"$HOST_IP"':2380"' /etc/default/etcd
    sed -i '$a  ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"' /etc/default/etcd
    sed -i '$a  ETCD_INITIAL_CLUSTER_STATE="new"' /etc/default/etcd
    systemctl enable etcd && systemctl start etcd
}

function_ub16_keystone()
{
    #openstack keystone install
    USERNAME="root"
    mysql -u$USERNAME -p$PASSWORD -e "CREATE DATABASE keystone"
    mysql -u$USERNAME -p$PASSWORD -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '${PASSWORD}'"
    mysql -u$USERNAME -p$PASSWORD -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '${PASSWORD}'"

    apt install -y keystone  apache2 libapache2-mod-wsgi

    sed -i '/^\[database\]/a\connection = mysql+pymysql://keystone:'"$PASSWORD"'@'"$HOSTNAME"'/keystone' /etc/keystone/keystone.conf
    sed -i '/^\[token\]/a\provider = fernet' /etc/keystone/keystone.conf

    su -s /bin/sh -c "keystone-manage db_sync" keystone

    keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
    keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
    keystone-manage bootstrap --bootstrap-password $PASSWORD \
     --bootstrap-admin-url http://$HOSTNAME:5000/v3/ \
     --bootstrap-internal-url http://$HOSTNAME:5000/v3/ \
     --bootstrap-public-url http://$HOSTNAME:5000/v3/ \
     --bootstrap-region-id RegionOne
    
    sed -i '$a ServerName '"$HOSTNAME"'' /etc/apache2/apache2.conf
    #echo "ServerName controller" >> /etc/httpd/conf/httpd.conf
    service apache2 restart

    if [ -f /home/admin-openrc ]
        then
          sed -i '/^/,$d' /home/admin-openrc
    else
        touch /home/admin-openrc
    fi
    echo "export OS_USERNAME=admin" >> /home/admin-openrc
    sed -i '$a export OS_PASSWORD='"$PASSWORD"''    /home/admin-openrc
    echo "export OS_PROJECT_NAME=admin" >> /home/admin-openrc
    echo "export OS_USER_DOMAIN_NAME=Default" >> /home/admin-openrc
    echo "export OS_PROJECT_DOMAIN_NAME=Default" >> /home/admin-openrc
    #echo "export OS_AUTH_URL=http://controller:5000/v3" >> /home/admin-openrc
    sed -i '$a export OS_AUTH_URL=http://'"$HOSTNAME"':5000/v3' /home/admin-openrc
    echo "export OS_IDENTITY_API_VERSION=3" >> /home/admin-openrc
    echo "export OS_IMAGE_API_VERSION=2"    >>/home/admin-openrc
    source /home/admin-openrc
    openstack project create --domain default --description "Service Project" service

}

function_ub16_glance()
{
# Image service install for control node
    USERNAME="root"
    mysql -u$USERNAME -p$PASSWORD -e "CREATE DATABASE glance"
    mysql -u$USERNAME -p$PASSWORD -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '${PASSWORD}'"
    mysql -u$USERNAME -p$PASSWORD -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '${PASSWORD}'"

    openstack user create --domain default --password $PASSWORD glance
    openstack role add --project service --user glance admin
    openstack service create --name glance --description "OpenStack Image" image
    openstack endpoint create --region RegionOne image public http://$HOSTNAME:9292
    openstack endpoint create --region RegionOne image internal http://$HOSTNAME:9292
    openstack endpoint create --region RegionOne image admin http://$HOSTNAME:9292
    apt install -y glance

#config glance-api.conf
    sed -i '/^\[database\]/a\connection = mysql+pymysql://glance:'"$PASSWORD"'@'"$HOSTNAME"'/glance' /etc/glance/glance-api.conf

    sed -i '/^\[keystone_authtoken\]/a\password = '"$PASSWORD"''      /etc/glance/glance-api.conf
    sed -i '/^\[keystone_authtoken\]/a\username = glance' /etc/glance/glance-api.conf
    sed -i '/^\[keystone_authtoken\]/a\project_name = service' /etc/glance/glance-api.conf
    sed -i '/^\[keystone_authtoken\]/a\user_domain_name = Default' /etc/glance/glance-api.conf
    sed -i '/^\[keystone_authtoken\]/a\project_domain_name = Default' /etc/glance/glance-api.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_type = password' /etc/glance/glance-api.conf
    sed -i '/^\[keystone_authtoken\]/a\memcached_servers = '"$HOSTNAME"':11211' /etc/glance/glance-api.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_url = http://'"$HOSTNAME"':5000' /etc/glance/glance-api.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_uri  = http://'"$HOSTNAME"':5000'    /etc/glance/glance-api.conf

    sed -i '/^\[paste_deploy\]/a\flavor = keystone' /etc/glance/glance-api.conf

    sed -i '/^\[glance_store\]/a\filesystem_store_datadir = /var/lib/glance/images/' /etc/glance/glance-api.conf
    sed -i '/^\[glance_store\]/a\default_store = file'         /etc/glance/glance-api.conf
    sed -i '/^\[glance_store\]/a\stores = file,http' /etc/glance/glance-api.conf


#config glance-registry.conf
    sed -i '/^\[database\]/a\connection = mysql+pymysql://glance:'"$PASSWORD"'@'"$HOSTNAME"'/glance' /etc/glance/glance-registry.conf

    sed -i '/^\[keystone_authtoken\]/a\password = '"$PASSWORD"''      /etc/glance/glance-registry.conf
    sed -i '/^\[keystone_authtoken\]/a\username = glance' /etc/glance/glance-registry.conf
    sed -i '/^\[keystone_authtoken\]/a\project_name = service' /etc/glance/glance-registry.conf
    sed -i '/^\[keystone_authtoken\]/a\user_domain_name = Default' /etc/glance/glance-registry.conf
    sed -i '/^\[keystone_authtoken\]/a\project_domain_name = Default' /etc/glance/glance-registry.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_type = password' /etc/glance/glance-registry.conf
    sed -i '/^\[keystone_authtoken\]/a\memcached_servers = '"$HOSTNAME"':11211' /etc/glance/glance-registry.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_url = http://'"$HOSTNAME"':5000' /etc/glance/glance-registry.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_uri  = http://'"$HOSTNAME"':5000'    /etc/glance/glance-registry.conf

    sed -i '/^\[paste_deploy\]/a\flavor = keystone' /etc/glance/glance-registry.conf

    su -s /bin/sh -c "glance-manage db_sync" glance

#glance final installation
    service glance-registry restart
    service glance-api restart

}

function_ub16_nova_for_controller()
{

#nova install  install for controller node
    USERNAME="root"
    mysql -u$USERNAME -p$PASSWORD -e  "CREATE DATABASE nova_api"
    mysql -u$USERNAME -p$PASSWORD -e  "CREATE DATABASE nova"
    mysql -u$USERNAME -p$PASSWORD -e  "CREATE DATABASE nova_cell0"
#grant privileges
    mysql -u$USERNAME -p$PASSWORD -e  "GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'localhost' IDENTIFIED BY '${PASSWORD}'"
    mysql -u$USERNAME -p$PASSWORD -e  "GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'%' IDENTIFIED BY '${PASSWORD}'"
    mysql -u$USERNAME -p$PASSWORD -e  "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY '${PASSWORD}'"
    mysql -u$USERNAME -p$PASSWORD -e  "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY '${PASSWORD}'"
    mysql -u$USERNAME -p$PASSWORD -e  "GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'localhost' IDENTIFIED BY '${PASSWORD}'"
    mysql -u$USERNAME -p$PASSWORD -e  "GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'%' IDENTIFIED BY '${PASSWORD}'"

#create user nova
    openstack user create --domain default --password $PASSWORD  nova
    openstack role add --project service --user nova admin
    openstack service create --name nova  --description "OpenStack Compute" compute

#endpoint create
    openstack endpoint create --region RegionOne compute public http://$HOSTNAME:8774/v2.1
    openstack endpoint create --region RegionOne compute internal http://$HOSTNAME:8774/v2.1
    openstack endpoint create --region RegionOne compute admin http://$HOSTNAME:8774/v2.1


    openstack user create --domain default --password $PASSWORD placement
    openstack role add --project service --user placement admin
#placement endpoint create

    openstack service create --name placement --description "Placement API" placement
    openstack endpoint create --region RegionOne placement public http://$HOSTNAME:8778
    openstack endpoint create --region RegionOne placement internal http://$HOSTNAME:8778
    openstack endpoint create --region RegionOne placement admin http://$HOSTNAME:8778

#nova package install

    apt install -y nova-api nova-conductor nova-consoleauth \
     nova-novncproxy nova-scheduler nova-placement-api
    #nova config
    sed -i '/^\[DEFAULT\]/a\firewall_driver = nova.virt.firewall.NoopFirewallDriver' /etc/nova/nova.conf
    sed -i '/^\[DEFAULT\]/a\use_neutron = True' /etc/nova/nova.conf
    sed -i '/^\[DEFAULT\]/a\my_ip = '"$HOST_IP"'' /etc/nova/nova.conf
    sed -i '/^\[DEFAULT\]/a\transport_url = rabbit://openstack:'"$PASSWORD"'@'"$HOSTNAME"'' /etc/nova/nova.conf
    sed -i '/^log_dir/d' /etc/nova/nova.conf


    sed -i '/^\[api_database\]/a\connection = mysql+pymysql://nova:'"$PASSWORD"'@'"$HOSTNAME"'/nova_api' /etc/nova/nova.conf
    sed -i '/^\[database\]/a\connection = mysql+pymysql://nova:'"$PASSWORD"'@'"$HOSTNAME"'/nova' /etc/nova/nova.conf
    #sed -i '/^\[placement_database\]/a\connection = mysql+pymysql://placement:'"$PASSWORD"'@'"$HOSTNAME"'/placement' /etc/nova/nova.conf
    sed -i '/^\[api\]/a\auth_strategy = keystone' /etc/nova/nova.conf
#keystone authtoken
    sed -i '/^\[keystone_authtoken\]/a\password = '"$PASSWORD"''      /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\username = nova' /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\project_name = service' /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\user_domain_name = Default' /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\project_domain_name = Default'  /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_type = password' /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\memcached_servers = '"$HOSTNAME"':11211' /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_url = http://'"$HOSTNAME"':5000/v3'    /etc/nova/nova.conf


#vnc server
    sed -i '/^\[vnc\]/a\server_proxyclient_address = $my_ip' /etc/nova/nova.conf
    sed -i '/^\[vnc\]/a\server_listen = $my_ip' /etc/nova/nova.conf
    sed -i '/^\[vnc\]/a\enabled = true' /etc/nova/nova.conf

    sed -i '/^\[glance\]/a\api_servers = http://'"$HOSTNAME"':9292' /etc/nova/nova.conf
    sed -i '/^\[oslo_concurrency\]/a\lock_path = /var/lib/nova/tmp' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\password = '"$PASSWORD"'' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\username = placement' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\auth_url = http://'"$HOSTNAME"':5000/v3' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\user_domain_name = Default' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\auth_type = password' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\project_name = service' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\project_domain_name = Default' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\os_region_name = RegionOne' /etc/nova/nova.conf
    sed -i '/^\[scheduler\]/a\discover_hosts_in_cells_interval = 300'  /etc/nova/nova.conf

    su -s /bin/sh -c "nova-manage api_db sync" nova
    su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova
    su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova
    su -s /bin/sh -c "nova-manage db sync" nova

    service nova-api restart
    service nova-consoleauth restart
    service nova-scheduler restart
    service nova-conductor restart
    service nova-novncproxy restart
}


function_ub16_neutron_for_controller()
{

    #neutron install for control node
    USERNAME="root"
    mysql -u$USERNAME -p$PASSWORD -e  "CREATE DATABASE neutron"
    mysql -u$USERNAME -p$PASSWORD -e  "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '${PASSWORD}'"
    mysql -u$USERNAME -p$PASSWORD -e  "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '${PASSWORD}'"
    openstack user create --domain default --password $PASSWORD  neutron
    openstack role add --project service --user neutron admin

    openstack service create --name neutron  --description "OpenStack Networking" network

#endpoint set for neutron
    openstack endpoint create --region RegionOne network public http://$HOSTNAME:9696
    openstack endpoint create --region RegionOne network internal http://$HOSTNAME:9696
    openstack endpoint create --region RegionOne network admin http://$HOSTNAME:9696

    apt install -y neutron-server neutron-plugin-ml2 \
      neutron-openvswitch-agent neutron-l3-agent neutron-dhcp-agent \
      neutron-metadata-agent

#neutron config file
    sed -i '/^\[database\]/a\connection = mysql+pymysql://neutron:'"$PASSWORD"'@'"$HOSTNAME"'/neutron' /etc/neutron/neutron.conf
    sed -i '/^\[DEFAULT\]/a\core_plugin = ml2' /etc/neutron/neutron.conf
    sed -i '/^core_plugin/a\service_plugins=router' /etc/neutron/neutron.conf
    sed -i '/^service_plugins/a\allow_overlapping_ips = true'  /etc/neutron/neutron.conf
    sed -i '/^allow_overlapping_ips/a\transport_url = rabbit://openstack:'"$PASSWORD"'@'"$HOSTNAME"'' /etc/neutron/neutron.conf
    sed -i '/^transport_url/a\auth_strategy = keystone' /etc/neutron/neutron.conf
    sed -i '/^auth_strategy/a\notify_nova_on_port_status_changes = true' /etc/neutron/neutron.conf
    sed -i '/^notify_nova_on_port_status_changes/a\notify_nova_on_port_data_changes = true' /etc/neutron/neutron.conf

#keysstone_auth for neutron
    sed -i '/^\[keystone_authtoken\]/a\password = '"$PASSWORD"'' /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\username = neutron' /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\project_name = service' /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\user_domain_name = default' /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\project_domain_name = default' /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_type = password' /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\memcached_servers = '"$HOSTNAME"':11211'          /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_url = http://'"$HOSTNAME"':5000' /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_uri = http://'"$HOSTNAME"':5000' /etc/neutron/neutron.conf

#set nova section in neutron.conf
    sed -i '/^\[nova\]/a\password = '"$PASSWORD"'' /etc/neutron/neutron.conf
    sed -i '/^\[nova\]/a\username = nova' /etc/neutron/neutron.conf
    sed -i '/^\[nova\]/a\project_name = service' /etc/neutron/neutron.conf
    sed -i '/^\[nova\]/a\region_name = RegionOne' /etc/neutron/neutron.conf
    sed -i '/^\[nova\]/a\user_domain_name = default' /etc/neutron/neutron.conf
    sed -i '/^\[nova\]/a\project_domain_name = default' /etc/neutron/neutron.conf
    sed -i '/^\[nova\]/a\auth_type = password' /etc/neutron/neutron.conf
    sed -i '/^\[nova\]/a\auth_url = http://'"$HOSTNAME"':5000' /etc/neutron/neutron.conf

    sed -i '/^\[oslo_concurrency\]/a\lock_path = /var/lib/neutron/tmp' /etc/neutron/neutron.conf


#set ml2 plugin config file

    sed -i '/^\[ml2\]/a\type_drivers = flat,vlan,vxlan' /etc/neutron/plugins/ml2/ml2_conf.ini
    sed -i '/^type_drivers/a\tenant_network_types = vxlan' /etc/neutron/plugins/ml2/ml2_conf.ini
    sed -i '/^tenant_network_types/a\mechanism_drivers = openvswitch,l2population' /etc/neutron/plugins/ml2/ml2_conf.ini
    sed -i '/^mechanism_drivers/a\extension_drivers = port_security' /etc/neutron/plugins/ml2/ml2_conf.ini
    sed -i '/^\[ml2_type_vxlan\]/a\vni_ranges = 1:1000' /etc/neutron/plugins/ml2/ml2_conf.ini
    sed -i '/^\[securitygroup\]/a\enable_ipset = true' /etc/neutron/plugins/ml2/ml2_conf.ini

#set ovs agent config
    sed -i '/^\[ovs\]/a\tunnel_bridge = br-tun' /etc/neutron/plugins/ml2/openvswitch_agent.ini
    sed -i '/^tunnel_bridge/a\local_ip = '"$LOCAL_IP"'' /etc/neutron/plugins/ml2/openvswitch_agent.ini
    sed -i '/^local_ip/a\integration_bridge = br-int' /etc/neutron/plugins/ml2/openvswitch_agent.ini
    sed -i '/^\[agent\]/a\tunnel_types = vxlan' /etc/neutron/plugins/ml2/openvswitch_agent.ini
    sed -i '/^tunnel_types/a\l2_population = True' /etc/neutron/plugins/ml2/openvswitch_agent.ini
    sed -i '/^\[securitygroup\]/a\firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver' /etc/neutron/plugins/ml2/openvswitch_agent.ini
    sed -i '/^firewall_driver/a\enable_security_group = True' /etc/neutron/plugins/ml2/openvswitch_agent.ini

#l3 agent set
    sed -i '/^\[DEFAULT\]/a\interface_driver = openvswitch' /etc/neutron/l3_agent.ini

#dhcp agent set
    sed -i '/^\[DEFAULT\]/a\interface_driver = openvswitch' /etc/neutron/dhcp_agent.ini
    sed -i '/^interface_driver/a\dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq' /etc/neutron/dhcp_agent.ini
    sed -i '/^dhcp_driver/a\enable_isolated_metadata = True' /etc/neutron/dhcp_agent.ini

#set metadata
    sed -i '/^\[DEFAULT\]/a\nova_metadata_host = '"$HOSTNAME"'' /etc/neutron/metadata_agent.ini
    sed -i '/^nova_metadata_host/a\metadata_proxy_shared_secret = '"$PASSWORD"'' /etc/neutron/metadata_agent.ini

#set neutron section in nova.conf
    sed -i '/^\[neutron\]/a\metadata_proxy_shared_secret = '"$PASSWORD"'' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\service_metadata_proxy = true' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\password = '"$PASSWORD"'' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\username = neutron' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\project_name = service' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\region_name = RegionOne' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\user_domain_name = default' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\project_domain_name = default' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\auth_type = password' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\auth_url = http://'"$HOSTNAME"':5000' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\url = http://'"$HOSTNAME"':9696' /etc/nova/nova.conf


#write to db
    su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf \
      --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

    service nova-api restart

    service neutron-server restart
    service  neutron-openvswitch-agent restart
    service neutron-dhcp-agent restart
    service neutron-metadata-agent restart
    service neutron-l3-agent restart

}


function_ub16_dashboard()
{
#dashboard install
    apt install -y openstack-dashboard
    sed -i 's/^OPENSTACK_HOST.*/OPENSTACK_HOST = "'"$HOSTNAME"'"/' /etc/openstack-dashboard/local_settings.py
    sed -i "s/ALLOWED_HOSTS.*/ALLOWED_HOSTS = [\'*\']/" /etc/openstack-dashboard/local_settings.py
    sed -i "/^ALLOWED_HOSTS/a\SESSION_ENGINE = \'django.contrib.sessions.backends.cache\'" /etc/openstack-dashboard/local_settings.py
    sed -i '/^CACHES/,+5d' /etc/openstack-dashboard/local_settings.py
    tee >> /etc/openstack-dashboard/local_settings.py <<-'EOF'
CACHES = {
    'default': {
         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
EOF

    #sed -i   '$a        'LOCATION': '$HOSTNAME:11211','  /etc/openstack-dashboard/local_settings.py
    echo "    'LOCATION': '$HOSTNAME:11211',"  >> /etc/openstack-dashboard/local_settings.py
    echo "      }" >> /etc/openstack-dashboard/local_settings.py
    echo "}"  >>/etc/openstack-dashboard/local_settings.py
#
    sed -i 's/^#OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT.*/OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True/' /etc/openstack-dashboard/local_settings.py

    tee >> /etc/openstack-dashboard/local_settings.py <<-'EOF'
OPENSTACK_API_VERSIONS = {
        "identity": 3,
        "image": 2,
        "volume": 2,
        }  
EOF
    sed -i 's/^#OPENSTACK_KEYSTONE_DEFAULT_DOMAIN.*/OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = "Default"/' /etc/openstack-dashboard/local_settings.py
    sed -i 's/^OPENSTACK_KEYSTONE_DEFAULT_ROLE.*/OPENSTACK_KEYSTONE_DEFAULT_ROLE = "user"/' /etc/openstack-dashboard/local_settings.py

    sed -i '$a WSGIApplicationGroup %{GLOBAL}' /etc/apache2/conf-available/openstack-dashboard.conf
    service apache2 reload

}

#install function for compute node

function_ub16_nova_for_compute()
{
#nova compute install

apt install -y nova-compute
#configure nova.conf

if [ $controller -eq 0 ] ; then
    sed -i '/^\[DEFAULT\]/a\firewall_driver = nova.virt.firewall.NoopFirewallDriver' /etc/nova/nova.conf
    sed -i '/^\[DEFAULT\]/a\use_neutron = true' /etc/nova/nova.conf
    sed -i '/^\[DEFAULT\]/a\my_ip = '"$HOST_IP"'' /etc/nova/nova.conf
    sed -i '/^\[DEFAULT\]/a\transport_url = rabbit://openstack:'"$PASSWORD"'@'"$MASTERNAME"'' /etc/nova/nova.conf
    sed -i '/^\[api\]/a\auth_strategy = keystone' /etc/nova/nova.conf

    sed -i '/^\[keystone_authtoken\]/a\password = '"$PASSWORD"''   /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\username = nova'   /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\project_name = service'  /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\user_domain_name = Default'   /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\project_domain_name = Default'   /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_type = password'  /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\memcached_servers = '"$MASTERNAME"':11211'  /etc/nova/nova.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_url = http://'"$MASTERNAME"':5000/v3'  /etc/nova/nova.conf

#vnc section set

    sed -i '/^\[vnc\]/a\server_proxyclient_address = $my_ip' /etc/nova/nova.conf
    sed -i '/^\[vnc\]/a\server_listen = 0.0.0.0' /etc/nova/nova.conf
    sed -i '/^\[vnc\]/a\enabled = true' /etc/nova/nova.conf
    #glance section set

    sed -i '/^\[glance\]/a\api_servers = http://'"$MASTERNAME"':9292' /etc/nova/nova.conf
    sed -i '/^\[oslo_concurrency\]/a\lock_path = /var/lib/nova/tmp' /etc/nova/nova.conf

    #placement section
    sed -i '/^\[placement\]/a\password = '"$PASSWORD"'' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\username = placement' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\auth_url = http://'"$MASTERNAME"':5000/v3' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\user_domain_name = Default' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\auth_type = password' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\project_name = service' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\project_domain_name = Default' /etc/nova/nova.conf
    sed -i '/^\[placement\]/a\os_region_name = RegionOne' /etc/nova/nova.conf
fi

sed -i '/^\[vnc\]/a\novncproxy_base_url = http://'"$SERVER_IP"':6080/vnc_auto.html' /etc/nova/nova.conf
cpunum=`egrep -c '(vmx|svm)' /proc/cpuinfo`
if [ $cpunum -eq 0 ]
    then
    sed -i '/^\[libvirt\]/a\virt_type = qemu' /etc/nova/nova.conf
fi

service nova-compute restart

}


function_ub16_neutron_for_compute()
{
#neutron install in compute node
  apt-get install -y neutron-openvswitch-agent
#When install ALLINONE ,all these has been set while install controll modules
if [ $controller -eq 0 ] ; then

    sed -i '/^\[DEFAULT\]/a\transport_url = rabbit://openstack:'"$PASSWORD"'@'"$MASTERNAME"'' /etc/neutron/neutron.conf
    sed -i '/^\[DEFAULT\]/a\auth_strategy = keystone'  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\password = '"$PASSWORD"''  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\username = neutron'  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\project_name = service'  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\user_domain_name = default'  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\project_domain_name = default'  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_type = password'  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\memcached_servers = '"$MASTERNAME"':11211'  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_url = http://'"$MASTERNAME"':5000'  /etc/neutron/neutron.conf
    sed -i '/^\[keystone_authtoken\]/a\auth_uri = http://'"$MASTERNAME"':5000'  /etc/neutron/neutron.conf
    sed -i '/^\[oslo_concurrency\]/a\lock_path = /var/lib/neutron/tmp'  /etc/neutron/neutron.conf
fi
#set ovs agent config

sed -i '/^\[ovs\]/a\tunnel_bridge = br-tun' /etc/neutron/plugins/ml2/openvswitch_agent.ini
sed -i '/^tunnel_bridge/a\local_ip = '"$LOCAL_IP"'' /etc/neutron/plugins/ml2/openvswitch_agent.ini
sed -i '/^local_ip/a\integration_bridge = br-int' /etc/neutron/plugins/ml2/openvswitch_agent.ini
sed -i '/^integration_bridge/a\enable_tunneling = True' /etc/neutron/plugins/ml2/openvswitch_agent.ini
sed -i '/^\[agent\]/a\tunnel_types = vxlan' /etc/neutron/plugins/ml2/openvswitch_agent.ini
sed -i '/^tunnel_types/a\l2_population = True' /etc/neutron/plugins/ml2/openvswitch_agent.ini
sed -i '/^\[securitygroup\]/a\firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver' /etc/neutron/plugins/ml2/openvswitch_agent.ini
sed -i '/^firewall_driver/a\enable_security_group = True' /etc/neutron/plugins/ml2/openvswitch_agent.ini

#set neutron section in nova.conf
if [ $controller -eq 0 ] ; then
    sed -i '/^\[neutron\]/a\password = '"$PASSWORD"'' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\username = neutron' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\project_name = service' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\region_name = RegionOne' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\user_domain_name = default' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\project_domain_name = default' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\auth_type = password' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\auth_url = http://'"$MASTERNAME"':5000' /etc/nova/nova.conf
    sed -i '/^\[neutron\]/a\url = http://'"$MASTERNAME"':9696' /etc/nova/nova.conf
fi
#service start
service nova-compute restart
service  neutron-openvswitch-agent restart

}


